import { Ministry, State} from "@/types/server";

export const ministries: Ministry[] = [
  { id: 'ministry-agriculture', name: 'Federal Ministry of Agriculture and Rural Development' },
  { id: 'ministry-aviation', name: 'Federal Ministry of Aviation' },
  { id: 'ministry-budget', name: 'Federal Ministry of Budget and Economic Planning' },
  { id: 'ministry-commerce', name: 'Federal Ministry of Industry, Trade and Investment' },
  { id: 'ministry-comms', name: 'Federal Ministry of Communications, Innovation and Digital Economy' },
  { id: 'ministry-defence', name: 'Federal Ministry of Defence' },
  { id: 'ministry-education', name: 'Federal Ministry of Education' },
  { id: 'ministry-environment', name: 'Federal Ministry of Environment' },
  { id: 'ministry-fct', name: 'Federal Capital Territory Administration' },
  { id: 'ministry-finance', name: 'Federal Ministry of Finance' },
  { id: 'ministry-foreign', name: 'Federal Ministry of Foreign Affairs' },
  { id: 'ministry-health', name: 'Federal Ministry of Health and Social Welfare' },
  { id: 'ministry-housing', name: 'Federal Ministry of Housing and Urban Development' },
  { id: 'ministry-humanitarian', name: 'Federal Ministry of Humanitarian Affairs and Poverty Alleviation' },
  { id: 'ministry-information', name: 'Federal Ministry of Information and National Orientation' },
  { id: 'ministry-interior', name: 'Federal Ministry of Interior' },
  { id: 'ministry-justice', name: 'Federal Ministry of Justice' },
  { id: 'ministry-labour', name: 'Federal Ministry of Labour and Employment' },
  { id: 'ministry-petroleum', name: 'Federal Ministry of Petroleum Resources' },
  { id: 'ministry-power', name: 'Federal Ministry of Power' },
  { id: 'ministry-science', name: 'Federal Ministry of Science, Technology and Innovation' },
  { id: 'ministry-sports', name: 'Federal Ministry of Sports Development' },
  { id: 'ministry-tourism', name: 'Federal Ministry of Tourism' },
  { id: 'ministry-transport', name: 'Federal Ministry of Transportation' },
  { id: 'ministry-water', name: 'Federal Ministry of Water Resources and Sanitation' },
  { id: 'ministry-women', name: 'Federal Ministry of Women Affairs' },
  { id: 'ministry-works', name: 'Federal Ministry of Works' },
  { id: 'ministry-youth', name: 'Federal Ministry of Youth' },
];

export const states: State[] = [
  { id: 'state-abia', name: 'Abia', capital: 'Umuahia' },
  { id: 'state-adamawa', name: 'Adamawa', capital: 'Yola' },
  { id: 'state-akwa-ibom', name: 'Akwa Ibom', capital: 'Uyo' },
  { id: 'state-anambra', name: 'Anambra', capital: 'Awka' },
  { id: 'state-bauchi', name: 'Bauchi', capital: 'Bauchi' },
  { id: 'state-bayelsa', name: 'Bayelsa', capital: 'Yenagoa' },
  { id: 'state-benue', name: 'Benue', capital: 'Makurdi' },
  { id: 'state-borno', name: 'Borno', capital: 'Maiduguri' },
  { id: 'state-cross-river', name: 'Cross River', capital: 'Calabar' },
  { id: 'state-delta', name: 'Delta', capital: 'Asaba' },
  { id: 'state-ebonyi', name: 'Ebonyi', capital: 'Abakaliki' },
  { id: 'state-edo', name: 'Edo', capital: 'Benin City' },
  { id: 'state-ekiti', name: 'Ekiti', capital: 'Ado-Ekiti' },
  { id: 'state-enugu', name: 'Enugu', capital: 'Enugu' },
  { id: 'state-gombe', name: 'Gombe', capital: 'Gombe' },
  { id: 'state-imo', name: 'Imo', capital: 'Owerri' },
  { id: 'state-jigawa', name: 'Jigawa', capital: 'Dutse' },
  { id: 'state-kaduna', name: 'Kaduna', capital: 'Kaduna' },
  { id: 'state-kano', name: 'Kano', capital: 'Kano' },
  { id: 'state-katsina', name: 'Katsina', capital: 'Katsina' },
  { id: 'state-kebbi', name: 'Kebbi', capital: 'Birnin Kebbi' },
  { id: 'state-kogi', name: 'Kogi', capital: 'Lokoja' },
  { id: 'state-kwara', name: 'Kwara', capital: 'Ilorin' },
  { id: 'state-lagos', name: 'Lagos', capital: 'Ikeja' },
  { id: 'state-nasarawa', name: 'Nasarawa', capital: 'Lafia' },
  { id: 'state-niger', name: 'Niger', capital: 'Minna' },
  { id: 'state-ogun', name: 'Ogun', capital: 'Abeokuta' },
  { id: 'state-ondo', name: 'Ondo', capital: 'Akure' },
  { id: 'state-osun', name: 'Osun', capital: 'Osogbo' },
  { id: 'state-oyo', name: 'Oyo', capital: 'Ibadan' },
  { id: 'state-plateau', name: 'Plateau', capital: 'Jos' },
  { id: 'state-rivers', name: 'Rivers', capital: 'Port Harcourt' },
  { id: 'state-sokoto', name: 'Sokoto', capital: 'Sokoto' },
  { id: 'state-taraba', name: 'Taraba', capital: 'Jalingo' },
  { id: 'state-yobe', name: 'Yobe', capital: 'Damaturu' },
  { id: 'state-zamfara', name: 'Zamfara', capital: 'Gusau' },
  { id: 'state-fct', name: 'Federal Capital Territory', capital: 'Abuja' },
];
